config/routes.rb
Rails.application.routes.draw do
root 'boards#index'

resources :boards do
resources :tasks
end
resources :tasks do
resources :lists
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :tasks

  #methods
def self.all_board(id)
  Board.find_by_sql("

    SELECT *
    FROM boards AS b
    WHERE b.id = #{id}

    ")

end


end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :board
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
 before_action :set_board, only: [:show, :edit, :update, :destroy]

  def index
    @boards = Board.all_board(:id)
  end

  def show
  end

  def new
    @board = Board.new
    render :new
  end
  def edit
    render :edit
  end
  def create
    @board = Board.new(board_params)

    if @board.save
        redirect_to boards_path
      else
        render :new
    end
  end
  def update
    if @board.update(board_params)
      redirect_to @board
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path

  end
  private
  def set_board
    @board = Board.find(params[:id])
  end
  def board_params
      params.require(:board).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_task
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = @task.lists
  
  end

  def show
  end

  def new
    @list = @task.lists.new
    render :new
  end
  def create
    @list = @task.lists.new(list_params)
    if @list.save
      redirect_to task_list_path(@task.id, @list.id)
    else
      render :new
    end
  end
  def update
    if @list.update(list_params)
      redirect_to task_list_path(@task, @list)
    else
      render :edit
    end
  end
  def destroy
    @list.destroy
    redirect_to task_lists_path(@task)
  end
  def set_task
    @task = Task.find(params[:task_id])

  end
  def set_list
    @list = @task.lists.find(params[:id])
  end
  def list_params
    params.require(:list).permit(:name, :note, :state)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_board
before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = @board.tasks
  end

  def show
  end

  def new
    @task = @board.tasks.new
    render :new
  end
  def create
    @task = @board.tasks.new(task_params)
    if @task.save
      redirect_to [@board, @task]
    else
      render :new
    end
  end
  def edit
    render :edit

  end
  def update
    if @task.update(task_params)
      redirect_to board_task_path(@board, @task)
    else
      render :edit
    end
  end
  def destroy
    @task.destroy
    redirect_to board_tasks_path(@board)
  end
  private
  def set_board
    @board = Board.find(params[:board_id])
  end
  def set_task
    @task = @board.tasks.find(params[:id])
  end
  def task_params
    params.require(:task).permit(:name, :dept)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/edit.html.erb
<h1>edit board</h1>
<br>
<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: "board name" %>
</div>
<%= f.submit %>
<% end %>

app/views/boards/index.html.erb
<h1>boards</h1>

<ul>
  <% @boards.each do |board|  %>
  <li>
    <%= link_to board.name, board, class: "item" %>
  </li>
  <% end %>
</ul>

app/views/boards/new.html.erb
<h1>make a new board</h1>

<%= form_with(model: @board, local: true, class: "ui form") do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: "board name" %>
</div>
<%= f.submit %>
<% end %>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>
<br>
<p>what would you like to do</p>

<%= link_to 'view tasks', board_tasks_path(@board) %>
<br>
<%= link_to 'edit board', edit_board_path(@board) %>
<br>
<%= link_to 'delete board', @board, method: :delete %>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
<%= link_to 'all boards', root_path, class: 'item' %>
<%= link_to 'new boards', new_board_path, class: 'item' %>




</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
    <%= render 'layouts/navbar' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1><%= @task.name %><%= @list.name %></h1>
<br>
<%= form_for [@task, @list] do |f| %>
<%= f.label :name %>
<%= f.text_field :name, required: true, autofocus: true %>
<br>
<p>state of affairs: <%= f.select :state, ['urgent', 'in progress','no started'] %></p>
<%= f.label :note %>
<%= f.text_field :note, required: true %>
<%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>click a list to view notes</h1>

<%= link_to 'back to tasks', board_path(@board) %>
<br>

<%= link_to 'create a new list', new_task_path(@task) %>
<ul>
  <% @lists.each do |list| %>
  <li>
    <%= link_to list.name, [@task, list] %>
  </li>
  <% end %>
</ul>
<h2><% @inprogress.each do |inprogress| %></h2>
<li>
  <%= inprogress.lists %>
  <br>
  <%= link_to 'Remove', task_list_path(@task, inprogress), method: :delete %>
</li>
<% end %>

app/views/lists/new.html.erb
<h1>Lists Item</h1>
<%= form_for [@task, @list] do |f| %>
<%= f.label :name %>
<%= f.text_field :name, required: true, autofocus: true %>
<br>
<p>state of affairs: <%= f.select :state, ['urgent', 'in progress','no started'] %></p>
<%= f.label :note %>
<%= f.text_field :note, required: true %>
<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @task.name %> & <%= @list.name %></h1>
<h3><%= @list.note %>,     <br>   state:  <%= @list.state %></h3>
<%= link_to 'Edit list item', edit_task_list_path([@task, @list]) %>
<%= link_to 'Delete', [@task, @list], method: :delete %>
<%= link_to 'Back To Tasks', task_lists_path(@task) %>

app/views/tasks/edit.html.erb
<h1>edit task</h1>

<%= form_for [@board, @task] do |f| %>
<%= f.label :name %>
<h2>division responsible:  <%= f.select :dept, ['corporate', 'IT', 'human resource', 'public relation'] %></h2>
<%= f.text_field :name, required: true, autofocus: true %>
<% end %>

app/views/tasks/index.html.erb
<h1>click on a task to view the list</h1>

<%= link_to 'create a new task', new_board_task_path %>
<ul>
  <% @tasks.each do |task| %>
  <li>
    <%= link_to task.name, [@board, task] %>
  </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Make a new task.</h1>
<br>
<%= form_for [@board, @task] do |f| %>
<%= f.label :name %>
<h2>division responsible:  <%= f.select :dept, ['corporate', 'IT', 'human resource', 'public relation'] %></h2>
<%= f.text_field :name, required: true, autofocus: true %>
<%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @board.name %> - <%= @task.name %></h1>

<%= link_to 'edit task', edit_board_task_path([@board, @task]) %>
<%= link_to 'Delete task', [@board, @task], method: :delete %>
<%= link_to 'back to tasks', board_tasks_path(@board) %>
<br>
<%= link_to 'add a list item', new_task_list_path(@task) %>